baseURL = "https://eruditedatasolutions.com/"
languageCode = "en-us"
title = "Data Solutions | Dedicated to helping businesses making data-driven decisions"
theme = "navigator-hugo"
summaryLength = 10

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = ""

enableGitInfo = false
pygmentsCodeFences = true

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "en"

# Site Params
[params]
logo = "images/erudite_logo.png"


# meta data
author = "Meg Oshima"
description = "This is meta description"

title = "Data Solutions"
dateFormat = "January 2, 2006"

home = "Home"
menufixed = false

footerDescription = "To empower businesses with the skills and support to embrace the potential of their data."
footerServiceTitle = "Service"
footerQuicklinkTitle = "Quicklinks"
footerAboutTitle = "Mission"
footerSubscribeTitle = "Subscribe"

# Hero Area Section
[params.hero]
enable  = true
heading = "Providing data-driven solutions for modern problems"
description = ""
button  = true
btnText = "Learn More"
btnURL  = "./service"
videoThumb = "images/slider/woman_working.jpg"
videoURL   = "https://www.youtube.com/embed/g3-VxLQO7do"

# About 2 Section
[params.aboutSm]
enable  = true
title   = "We use data-driven research to help businesses reach their full potential."
description = "We collaborate with businesses to develop the frameworks and skills necessary to harness the data available to them. Analyzing that data allows a company to better understand market trends and predict client behavior. It can also drive decision making to ensure the business is making profitable choices."

# Blog Section On Homepage
[params.blog]
enable  = true
topTitle= ""
title   = "Recent Posts"
subtitle= ""

# Contact Section
[params.contact]
enable  = true
topTitle= "DROP US A NOTE"
title   = "Contact Us."
subtitle= "If you are interested in a training course or our consulting services, send us a request. We look forward to working with you!"
address = "Ocean Springs, MS"
phone   = "(843) 902 9841"
twitter = "https://twitter.com/"
youtube= "https://www.youtube.com/channel/UC-1ICtrxPozDV8KMKHOQ13w?view_as=subscriber"
instagram= "https://www.instagram.com/"
mapLatitude = "30.412735"
mapLongitude= " -88.802957"
mapMarker   = "images/marker.png"

# Call to Action Section on About Page
[params.cta]
enable  = true
bg      = "images/call-to-action/call-to-action-bg-2.jpg"
title   = "Let's Work Together"
subtitle= "For all of your data science and analytics needs, we are here to help."
btnText = "Contact Us"

# We Used Themefisher Icon font for Icon, for more details check this github repository - https://github.com/themefisher/themefisher-font

# Site Menus
[menu]
# Navbar Menus
[[menu.nav]]
name    = "about"
url     = "about"
weight  = 2
[[menu.nav]]
name    = "service"
url     = "service"
weight  = 3
[[menu.nav]]
name    = "portfolio"
url     = "portfolio"
weight  = 4
[[menu.nav]]
name    = "blog"
url     = "blog"
weight  = 5
[[menu.nav]]
name    = "contact"
url     = "contact"
weight  = 6

# Footer Service Menu
[[menu.service]]
name    = "training"
url     = "service"
weight  = 1
[[menu.service]]
name    = "dashboard"
url     = "service"
weight  = 2
[[menu.service]]
name    = "shiny"
url     = "service"
weight  = 3

# Footer Quick links Menu
[[menu.quicklink]]
name    = "about"
url     = "about"
weight  = 1
[[menu.quicklink]]
name    = "faqs"
url     = "about"
weight  = 2
[[menu.quicklink]]
name    = "work"
url     = "contact"
weight  = 3
[[menu.quicklink]]
name    = "rbloggers"
url     = "https://www.r-bloggers.com/"
weight  = 4
